name: Frontend Lint Action

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  frontend-lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./estudo_angular2

    steps:
      - name: Clonar o repositório
        uses: actions/checkout@v4

      - name: Configurar o Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: './estudo_angular2/package-lock.json'

      - name: Instalar dependências
        run: npm ci

      - name: Executar Lint no Angular
        run: npm run lint